;; Paths & packages

(add-to-list 'load-path "~/.emacs.d/enzuru/features")
(add-to-list 'load-path "~/.emacs.d/enzuru/modes")
(add-to-list 'load-path "~/.emacs.d/enzuru/preferences")
(add-to-list 'load-path "~/.emacs.d/enzuru/setup")
(add-to-list 'load-path "~/.emacs.d/enzuru/operating-systems")
(add-to-list 'load-path "~/.emacs.d/enzuru/themes")
(add-to-list 'load-path "~/.emacs.d/elpa/exwm-0.24")
(add-to-list 'load-path "~/.emacs.d/elpa/xelb-0.18")

(load-library "enzuru-packages")

;; Features

(load-library "enzuru-autocompletion")
(load-library "enzuru-dashboard")
(load-library "enzuru-debugger")
(load-library "enzuru-file-manager")
(load-library "enzuru-help")
(load-library "enzuru-hyperlinking")
(load-library "enzuru-mail")
(load-library "enzuru-parens")
(load-library "enzuru-project-manager")
(load-library "enzuru-scheduler")
(load-library "enzuru-search")
(load-library "enzuru-server")
(load-library "enzuru-shell")
(load-library "enzuru-syntax-checking")
(load-library "enzuru-uname")
(load-library "enzuru-remote")
(load-library "enzuru-version-control")
(load-library "enzuru-writing")

;; Modes

(load-library "enzuru-c")
(load-library "enzuru-coffeescript")
(load-library "enzuru-common-lisp")
(load-library "enzuru-css")
(load-library "enzuru-docker")
(load-library "enzuru-emacs-lisp")
(load-library "enzuru-feature")
(load-library "enzuru-fountain")
(load-library "enzuru-haskell")
(load-library "enzuru-javascript")
(load-library "enzuru-json")
(load-library "enzuru-kotlin")
(load-library "enzuru-markdown")
(load-library "enzuru-objective-c")
(load-library "enzuru-org")
(load-library "enzuru-php")
(load-library "enzuru-puppet")
(load-library "enzuru-python")
(load-library "enzuru-ruby")
(load-library "enzuru-rust")
(load-library "enzuru-scheme")
(load-library "enzuru-swift")
(load-library "enzuru-web")
(load-library "enzuru-xml")
(load-library "enzuru-yaml")

;; Preferences

(load-library "enzuru-bars")
(load-library "enzuru-bell")
(load-library "enzuru-buffers")
(load-library "enzuru-customization")
(load-library "enzuru-frames")
(load-library "enzuru-highlighting")
(load-library "enzuru-margin")
(load-library "enzuru-modeline")
(load-library "enzuru-recent-files")
(load-library "enzuru-saving")
(load-library "enzuru-scrolling")
(load-library "enzuru-startup")
(load-library "enzuru-tabs")

;; Final setup

(load-library "enzuru-cleanup")
(load-library "enzuru-keys")
(load-library "enzuru-shutdown")
(load-library "enzuru-skin")

;; Operating systems

(if (eq system-type 'gnu/linux)
    (load-library "enzuru-linux"))
(if (eq system-type 'darwin)
    (load-library "enzuru-mac"))
(if (eq (uname) 'FreeBSD)
    (load-library "enzuru-freebsd"))
(if (eq (uname) 'OpenBSD)
    (load-library "enzuru-openbsd"))
(if (eq system-type 'windows-nt)
    (load-library "enzuru-windows"))
