;; -*- coding: utf-8; lexical-binding: t -*-

(defun enzuru-fitness-monthly-pounds
    (daily-calories daily-training-hours days-home days-outside)
  (let ((neat-home 2170)
        (neat-outside 2615)
        (burned-per-hour 400)
        (days-total (+ days-home days-outside)))
    (/ (- (* days-total daily-calories)
          (* days-total daily-training-hours burned-per-hour)
          (* days-home neat-home)
          (* days-outside neat-outside))
       3500.0)))

(defun success (message)
  (print (concat "SUCCESS: " message)))

(defun failure (message)
  (print (concat "FAILURE: " message)))

(defun enzuru-fitness-test-algo ()
  (let ((month "January 2023"))
    (if (eql (round (enzuru-fitness-monthly-pounds 2645 1.1 31 0)) 0)
        (success month)
      (failure month)))
  (let ((month "February 2023"))
    (if (eql (round (enzuru-fitness-monthly-pounds 2679 1.14 28 0)) 0)
        (success month)
      (failure month)))
  (let ((month "March 2023"))
    (if (eql (round (enzuru-fitness-monthly-pounds 2742 1.39 31 0)) -1)
        (success month)
      (failure month)))
  (let ((month "April 2023"))
    (if (eql (round (enzuru-fitness-monthly-pounds 2567 1.267 30 0)) -1)
        (success month)
      (failure month)))
  (let ((month "May 2023"))
    (if (eql (round (enzuru-fitness-monthly-pounds 2581 1.42 31 0)) -1)
        (success month)
      (failure month)))
  (let ((month "June 2023"))
    (if (eql (round (enzuru-fitness-monthly-pounds 2800 1.167 20 11)) 0)
        (success month)
      (failure month)))
  (let ((month "July 2023"))
    (if (eql (round (enzuru-fitness-monthly-pounds 2565 0.87 24 7)) 0)
        (success month)
      (failure month)))
  (let ((month "August 2023"))
    (if (eql (round (enzuru-fitness-monthly-pounds 2548 1.2 19 12)) -2)
        (success month)
      (failure month)))
  (let ((month "September 2023"))
    (if (eql (round (enzuru-fitness-monthly-pounds 2550 0.83 30 0)) 0)
        (success month)
      (failure month)))
  (let ((month "October 2023"))
    (if (eql (round (enzuru-fitness-monthly-pounds 2742 1.03 22 9)) 0)
        (success month)
      (failure month)))
  (let ((month "November 2023"))
    (if (eql (round (enzuru-fitness-monthly-pounds 2633 0.867 25 5)) 0)
        (success month)
      (failure month)))
  (let ((month "December 2023"))
    (if (eql (round (enzuru-fitness-monthly-pounds 2742 0.87 31 0)) 2)
        (success month)
      (failure month))))

(defun enzuru-fitness-vo2-max (ftp kilos)
  (+ (/ (* 10.8 ftp) kilos) 7))

(provide 'enzuru-fitness)
