(fringe-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)

(if (eq system-type 'darwin)
    (load-library "enzuru-exotica"))
(if (eq system-type 'windows-nt)
    (load-library "enzuru-arjen-grey"))
(if (eq system-type 'berkeley-unix)
    (load-library "enzuru-zenburn"))
(if (eq system-type 'gnu/linux)
    (load-library "enzuru-purple-haze"))
