(require 'diminish)

(eval-after-load "filladapt" '(diminish 'filladapt-mode))
(eval-after-load "paredit" '(diminish 'paredit-mode))
(eval-after-load "smartparens" '(diminish 'smartparens-mode))
(eval-after-load "counsel" '(diminish 'counsel-mode))
(eval-after-load "ivy" '(diminish 'ivy-mode))
(eval-after-load "company" '(diminish 'company-mode))
(eval-after-load "importmagic" '(diminish 'importmagic-mode))

(diminish 'magit-auto-revert-mode)
(diminish 'auto-revert-mode)
(diminish 'abbrev-mode)
(diminish 'yard-mode)
(diminish 'ruby-tools-mode)
(diminish 'eldoc-mode)
(diminish 'smartparens-mode)
(diminish 'ruby-refactor-mode)
(diminish 'paredit-mode)
(diminish 'projectile-mode)
(diminish 'smartparens-mode)
(diminish 'company-mode)
(diminish 'ivy-mode)
(diminish 'counsel-mode)
(diminish 'flycheck-mode)
(diminish 'importmagic-mode)
(diminish 'import)
(diminish 'which-key-mode)

(eval-after-load "robe" '(diminish 'robe-mode))
(eval-after-load "hideshow" '(diminish 'hs-minor-mode))
